---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: jusky
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "juskythehusky/spe-miniproject"  # Use your Docker Hub username
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator juskythehusky/spe-miniproject
